export type ListTypes = {
    active: boolean,
    createdAt: string,
    deleted: boolean,
    email: string,
    exampleOtherOne: string | null,
    exampleOtherOneId: number,
    exampleOtherTwo: string | null,
    exampleOtherTwoId: number,
    id: number,
    phone: string,
    typeBoolean: boolean,
    typeCurrency: number,
    typeDatetime: string,
    typeDecimal: number,
    typeEnum: string,
    typeInt: number,
    typeText: string,
    updatedAt: string,
}